export enum USER_TYPES {
  GET_USERS = "GET_USERS",
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  USER_ERROR = "USER_ERROR",
  USER_LOADING = "USER_LOADING",
  SET_CURRENT_USER = "SET_CURRENT_USER",
  CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER",
  SET_ENDERECO = "SET_ENDERECO",
}
