export enum USER_TYPES {
  GET_USERS_LOADING = "GET_USERS",
  GET_USERS_COMPLETED = "GET_USERS_LOADED",
  GET_USERS_ERROR = "GET_USERS_ERROR",
  CREATE_USER_LOADING = "CREATE_USER_LOADING",
  CREATE_USER_COMPLETED = "CREATE_USER_COMPLETED",
  CREATE_USER_ERROR = "CREATE_USER_ERROR",
  UPDATE_USER_LOADING = "UPDATE_USER_LOADING",
  UPDATE_USER_COMPLETED = "UPDATE_USER_COMPLETED",
  UPDATE_USER_ERROR = "CUPDATE_USER_ERROR",
  DELETE_USER_LOADING = "DELETE_USER_LOADING",
  DELETE_USER_COMPLETED = "DELETE_USER_COMPLETED",
  DELETE_USER_ERROR = "DELETE_USER_ERROR",
}
